name: Test bots

on:
  push:

jobs:
  get-changed:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            packages/common/**
            packages/bots/**

  test:
    if: needs.get-changed.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    needs: get-changed

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm -w @cdata/bots test
